id = "mach"
name = "Mach"
version = "0.3.0"
schema_version = 1
authors = ["octalide"]
description = "Mach language support for Zed — syntax highlighting, indentation, and LSP integration."
repository = "https://github.com/octalide/mach-zed"

[grammars.mach]
repository = "https://github.com/octalide/mach-tree-sitter"
rev = "9adbd90aa66b3c686f1576774959c2f0c24dcd62"

[language_servers.mls]
name = "Mach Language Server"
languages = ["Mach"]
